version: '3.8'

services:
  postgres:
    container_name: nest-graphql-postgres
    # change on production - prolly use bitnami image 
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest_graphql
      PG_DATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - ./cache:/data
