version: '3.8'

services:
  postgres:
    container_name: nest-graphql-postgres
    # change on production - prolly use bitnami image 
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest_graphql
      PG_DATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
